services:
  fiveminute:
    image: fiveminute:latest
    ports:
        - "80:8080"
    container_name: fiveminute
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db_postgresql_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fiveminute_db
     
      volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
