services:
  fiveminute:
    container_name: fiveminute
    image: fiveminute
    ports:
        - "80:8088"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db_postgresql_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fiveminute_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: